version: "3.9"
services:
  server:
    build: .
    volumes:
      - ./config:/usr/app/instant-poll/config:ro # if you want to change this, also set the env variable CONFIG
    ports:
      - "8090" # change if you set a different port in your config
